@startuml

namespace numopt {

    class NewtonBase {
        __ private members __
            - const size_t MAX_NO_ITERATIONS = 128
    }

    class Newton {
        __ private members __

    }

    class NewtonVector {
        __ private members __

        __ private methods __

        == constructors ==
            **Newton**(Eigen::VectorXd& x0, Eigen::VectorXd (*f)(), Eigen::MatrixXd (*J)())
        __ public methods __
            + Eigen::VectorXd& **solve**()
    }
}


numopt.Newton <|-- numopt.NewtonBase
numopt.NewtonVector <|-- numopt.NewtonBase



@enduml